scan_filter_chain:
- name: range 
  type: laser_filters/LaserScanRangeFilter 
  params: 
    use_message_range_limits: true 
    #upper_threshold: 4
    upper_replacement_value: 3.1
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 2
    max_angle: 178
    neighbors: 20
    window: 1
- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 0
    max_range: 4
    max_range_difference: 0.2
    filter_window: 2